/**
 * OpenAPI Types - SoloQ / Supabase
 *
 * This file is auto-generated by `bun run api:sync`.
 * Run: cd qa && bun run api:sync --url https://czuusjchqpgvanvbdrnz.supabase.co/rest/v1/ -t
 *
 * STUB: Replace with generated types after running api:sync.
 */

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface components {
  schemas: Record<string, unknown>
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type paths = Record<string, Record<string, any>>
